POST http://localhost:4004/odata/v4/catalog/insertSalesOrder
Content-Type: application/json

{
    "SALESORDER": [
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019082",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 1,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 150,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "SOLIDHPL",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "4799",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019083",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 2,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 400,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "SOLIDHPL",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7207",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019084",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 3,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 645,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "SOLIDHPL",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7241",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019085",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 1,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 1350,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "NATVENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "4799",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019086",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 2,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 440,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "NATVENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "4799",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7207",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019087",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 3,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 3000,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "NATVENEER",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7241",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "LAMINATE",
                    "CLASS": "VCD_1601",
                    "CLASS_NUM": 2499,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "VENEER",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019088",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-15",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 1,
            "PROD_AVAILABILITY_DT": "2026-04-16",
            "NET_VALUE": 1500,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-15",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "4799",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H1",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019089",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-27",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 2,
            "PROD_AVAILABILITY_DT": "2026-04-28",
            "NET_VALUE": 2400,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-27",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7207",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H2",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019090",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-27",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 3,
            "PROD_AVAILABILITY_DT": "2026-04-28",
            "NET_VALUE": 3600,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-27",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7241",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H3",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        },
        {
            "MANDT": "",
            "SALES_DOCUMENT": "0000019091",
            "SALES_DOCUMENT_ITEM": 100001,
            "DOC_CREATED_DATE": "2026-04-27",
            "SCHEDULE_LINE_NO": 1,
            "PRODUCT_ID": "VCD_1600",
            "MATERIAL_VARIANT": "",
            "REASON_4REJECTION": "",
            "UOM": "EA",
            "CONFIRMED_QTY": 0,
            "QTY_UNITS": 4,
            "PROD_AVAILABILITY_DT": "2026-04-28",
            "NET_VALUE": 4800,
            "CUSTOMER_GROUP": "01",
            "LOCATION_ID": "1600",
            "SALES_ORG": "0001",
            "DISTR_CHANNEL": "01",
            "DIVISION": "01",
            "SAL_DOCU_TYPE": "TA",
            "ITEM_CREATED_DATE": "2026-04-27",
            "ITEM_CHANGE_DATE": "0000-00-00",
            "OPEN_ORDER": "Y",
            "CHARG": "",
            "IBP_CUSTOMER": "",
            "NOT_PLANNING": "",
            "ON_HAND_STOCK": "N",
            "IN_TRANSIT": "",
            "SHIP_FROM_LOC": "",
            "RESERVE_FIELD1": "",
            "RESERVE_FIELD2": "",
            "RESERVE_FIELD3": "",
            "STOCK_LOC": "",
            "TRANS_TO_LOC": "",
            "TRANS_FROM_LOC": "",
            "DELETE_FLAG": "",
            "CHANGED_DATE": "2026-04-28",
            "CHANGED_TIME": "14:22:18",
            "CHANGED_BY": "GANGADHAR",
            "CREATED_DATE": "2026-04-28",
            "CREATED_TIME": "14:22:18",
            "CREATED_BY": "GANGADHAR",
            "ITEMS": [
                {
                    "CHARACTERSTIC": "Y0001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6229,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6245,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6246,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0003",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6225,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0004",
                    "CHARACTERSTIC_VALUE": "24H4",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6226,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0005",
                    "CHARACTERSTIC_VALUE": "PAINT",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6227,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "Z0006",
                    "CHARACTERSTIC_VALUE": "7360",
                    "CLASS": "VCD_1600",
                    "CLASS_NUM": 2498,
                    "CHARACTERSTIC_NUM": 6228,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZC001",
                    "CHARACTERSTIC_VALUE": "24H4",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6230,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD001",
                    "CHARACTERSTIC_VALUE": "24.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6247,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZD002",
                    "CHARACTERSTIC_VALUE": "48.0000",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6248,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                },
                {
                    "CHARACTERSTIC": "ZS001",
                    "CHARACTERSTIC_VALUE": "GLASS",
                    "CLASS": "VCD_1601_NEW",
                    "CLASS_NUM": 2506,
                    "CHARACTERSTIC_NUM": 6231,
                    "VALUE_NUM": 0,
                    "DELETE_FLAG": "",
                    "CHANGED_DATE": "2026-04-28",
                    "CHANGED_TIME": "14:22:18",
                    "CHANGED_BY": "GANGADHAR",
                    "CREATED_DATE": "2026-04-28",
                    "CREATED_TIME": "14:22:18",
                    "CREATED_BY": "GANGADHAR"
                }
            ]
        }
    ]
}